--DROP TABLE IF EXISTS UNIVERCITY;
 
/*CREATE TABLE UNIVERCITY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL
);
 
INSERT INTO UNIVERCITY (name, country) VALUES
  ('DU', 'INDIA'),
  ('JNU', 'INDIA'),
  ('OXFORD','UK');
*/